// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Body from "../components/Body.bs.js";
import * as React from "react";

function app() {
  return React.createElement(React.Fragment, {
              children: React.createElement(Body.make, {})
            });
}

export {
  app ,
}
/* Body Not a pure module */
