// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ImageHeader from "./ImageHeader.bs.js";

function header() {
  return React.createElement("div", undefined, React.createElement(ImageHeader.make, {}), React.createElement("div", undefined, "This is the header"));
}

export {
  header ,
}
/* react Not a pure module */
