// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function Body(props) {
  return React.createElement("div", {
              className: "flex flex-row bg-[#f3f1f9]"
            }, React.createElement("div", {
                  className: "flex flex-col"
                }, React.createElement("div", undefined, "This is the body"), React.createElement("div", undefined, React.createElement(Link, {
                          href: "/history",
                          children: "HISTóRIA"
                        }))));
}

var make = Body;

export {
  make ,
}
/* react Not a pure module */
