// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function footer() {
  return React.createElement("div", {
              className: "flex justify-center bg-[#f1f9f4] w-screen"
            }, React.createElement("div", undefined, "This is the footer"));
}

export {
  footer ,
}
/* react Not a pure module */
